jet:
  name: Jet-stage
  version: 1.0
  copyrightYear: 2021
  profile: /Users/cheng/JetStage/uploadPath
  addressEnable: false
  captchaType: math # 驗證碼類型 math or char
  demoEnabled: true

# 開發環境設定
server:
  port: 8080
  servlet:
    # AP access path
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      # Tomcat最大執行緒數量，預設為200
      max: 800
      # Tomcat啟動初始化的執行緒數量，預設為25
      min-spare: 30

spring:
  profiles:
    active: druid
  devtools:
    restart:
      enabled: true

# Token設定
token:
  # 可自定義標頭
  header: Authorization
  # 密鑰
  secret: jet-ndjrn3fn
  # 有效期限：預設30分
  expireTime: 30

# MyBatis設定
mybatis:
  # 搜尋指定的Package
  typeAliasesPackage: com.cheng.**.entity
  # 指定mapper.xml位置
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  # 載入設定檔
  configLocation: classpath:mybatis-config.xml

# Log
logging:
  level:
    com.cheng: debug
    org.springframework: warn